<a href="https://colab.research.google.com/github/theshashank1/cse-c5-3year-da/blob/main/cse_c5_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [13]:
df = pd.Series([1, 2, 3], index=['a', 'b', 'c'])

In [15]:
df.loc[['a', 'c']]

a    1
c    3
dtype: int64

In [5]:
df = pd.Series({"names": "sreeja", 'age': 23})

In [7]:
df.loc['names']

'sreeja'

In [9]:
df.iloc[0]

'sreeja'

In [24]:
df = pd.DataFrame([['shashank', 25], ['sreeja', 26], ['sai', 550]], columns=['name', 'marks'], index = ['a', 'b', 'c'])
df

       name  marks
a  shashank     25
b    sreeja     26
c       sai    550

In [25]:
df[['name', 'marks']].iloc[[0, 2]]

       name  marks
a  shashank     25
c       sai    550

In [26]:
df['name'].loc[['a', 'c']]

a    shashank
c         sai
Name: name, dtype: object

In [28]:
df = pd.DataFrame({
  'name': ['shashank', 'sreeja'],
  'marks':[25, 55]
})
df

       name  marks
0  shashank     25
1    sreeja     55

In [54]:
data = pd.read_csv('/content/zepto.csv')
data

,order_id,item,category,price,quantity,city,delivery_mins,order_date,plan
0,101,Milk,Dairy,62,2,Hyderabad,12,2025-01-15,Prime
1,102,Bread,Bakery,45,1,hyderabad,15,15-01-2025,NaN
2,103,maggi,Packaged Food,20,3,Bengaluru,10,2025-01-16,Free
3,104,Eggs (12),Dairy,₹84,1,Chennai,500,2025-01-16,Prime
4,105,Rice 5kg,Grocery,249,1,Hyderabad,18,16-01-2025,Free
5,106,Butter,Dairy,55,2,HYDERABAD,14,2025-01-17,NaN
6,107,PANEER,dairy,90,-1,Chennai,11,2025-01-17,Prime
7,108,Curd,Dairy,40,1,Bengaluru,9,2025-01-18,Free
8,109,Milk,Dairy,NaN,1,NaN,13,2025-01-18,Free
9,110,Bread,Bakery,45,0,hyderabad,16,2025-01-19,Prime
10,111,Oil 1L,Grocery,150,1,Hyderabad,-5,2025-01-19,NaN
11,101,Milk,Dairy,62,2,Hyderabad,12,2025-01-15,Prime

In [33]:
data.columns

Index(['order_id', 'item', 'category', 'price', 'quantity', 'city',
       'delivery_mins', 'order_date', 'plan'],
      dtype='object')

In [55]:
data['price'] = data['price'].str.replace('₹', '')

In [38]:
data['price'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 12 entries, 0 to 11
Series name: price
Non-Null Count  Dtype
--------------  -----
11 non-null     object
dtypes: object(1)
memory usage: 228.0+ bytes

In [60]:
data['price'] = data['price'].fillna(data['price'].mean())
data

,order_id,item,category,price,quantity,city,delivery_mins,order_date,plan
0,101,Milk,Dairy,62,2,Hyderabad,12,2025-01-15,Prime
1,102,Bread,Bakery,45,1,hyderabad,15,15-01-2025,NaN
2,103,maggi,Packaged Food,20,3,Bengaluru,10,2025-01-16,Free
3,104,Eggs (12),Dairy,84,1,Chennai,500,2025-01-16,Prime
4,105,Rice 5kg,Grocery,249,1,Hyderabad,18,16-01-2025,Free
5,106,Butter,Dairy,55,2,HYDERABAD,14,2025-01-17,NaN
6,107,PANEER,dairy,90,-1,Chennai,11,2025-01-17,Prime
7,108,Curd,Dairy,40,1,Bengaluru,9,2025-01-18,Free
8,109,Milk,Dairy,0,1,NaN,13,2025-01-18,Free
9,110,Bread,Bakery,45,0,hyderabad,16,2025-01-19,Prime
10,111,Oil 1L,Grocery,150,1,Hyderabad,-5,2025-01-19,NaN
11,101,Milk,Dairy,62,2,Hyderabad,12,2025-01-15,Prime

In [62]:
data['price'] = data['price'].astype(int)

In [63]:
data[['order_id', 'item', 'price']][data['price'] < 20]

   order_id  item  price
8       109  Milk      0

In [65]:
data['price'].mean()

np.float64(75.16666666666667)

In [66]:
data.groupby('category', as_index=False)['price'].mean()

        category  price
0         Bakery   45.0
1          Dairy   50.5
2        Grocery  199.5
3  Packaged Food   20.0
4          dairy   90.0

In [67]:
data.isnull().sum()

order_id         0
item             0
category         0
price            0
quantity         0
city             1
delivery_mins    0
order_date       0
plan             3
dtype: int64

In [68]:
data = data.dropna(subset='plan')

In [70]:
data.isnull().sum()

order_id         0
item             0
category         0
price            0
quantity         0
city             1
delivery_mins    0
order_date       0
plan             0
dtype: int64

In [71]:
data = data.dropna(subset = 'city')

In [72]:
data

,order_id,item,category,price,quantity,city,delivery_mins,order_date,plan
0,101,Milk,Dairy,62,2,Hyderabad,12,2025-01-15,Prime
2,103,maggi,Packaged Food,20,3,Bengaluru,10,2025-01-16,Free
3,104,Eggs (12),Dairy,84,1,Chennai,500,2025-01-16,Prime
4,105,Rice 5kg,Grocery,249,1,Hyderabad,18,16-01-2025,Free
6,107,PANEER,dairy,90,-1,Chennai,11,2025-01-17,Prime
7,108,Curd,Dairy,40,1,Bengaluru,9,2025-01-18,Free
9,110,Bread,Bakery,45,0,hyderabad,16,2025-01-19,Prime
11,101,Milk,Dairy,62,2,Hyderabad,12,2025-01-15,Prime

In [74]:
data.duplicated().sum()

np.int64(1)

In [75]:
data = data.drop_duplicates(keep='last')

In [76]:
data

,order_id,item,category,price,quantity,city,delivery_mins,order_date,plan
2,103,maggi,Packaged Food,20,3,Bengaluru,10,2025-01-16,Free
3,104,Eggs (12),Dairy,84,1,Chennai,500,2025-01-16,Prime
4,105,Rice 5kg,Grocery,249,1,Hyderabad,18,16-01-2025,Free
6,107,PANEER,dairy,90,-1,Chennai,11,2025-01-17,Prime
7,108,Curd,Dairy,40,1,Bengaluru,9,2025-01-18,Free
9,110,Bread,Bakery,45,0,hyderabad,16,2025-01-19,Prime
11,101,Milk,Dairy,62,2,Hyderabad,12,2025-01-15,Prime

In [77]:
data.drop(columns='order_date')

,order_id,item,category,price,quantity,city,delivery_mins,plan
2,103,maggi,Packaged Food,20,3,Bengaluru,10,Free
3,104,Eggs (12),Dairy,84,1,Chennai,500,Prime
4,105,Rice 5kg,Grocery,249,1,Hyderabad,18,Free
6,107,PANEER,dairy,90,-1,Chennai,11,Prime
7,108,Curd,Dairy,40,1,Bengaluru,9,Free
9,110,Bread,Bakery,45,0,hyderabad,16,Prime
11,101,Milk,Dairy,62,2,Hyderabad,12,Prime